### ISSUE TITLE
请问右键菜单怎么弄

### ISSUE THREAD

**Issue by yulianjie** [Beats0/mygalgame#1]
右键环形菜单无法调出，其他正常，用的是php7.2。

**Comment by Beats0** [comment]
没问题啊，浏览器问题吧, 不要开兼容模式

测试环境

chrome  v71.0      正常显示          顺滑流畅
Firefox   v63.03     正常显示          略卡
edge      v42          正常显示         巨卡
ie           v11          正常略不正常  较卡

PHP Version 7.2.2
